[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
# Future - necessary for the experimental "native build" of esp-idf-sys with ESP32C3. See also https://github.com/ivmarkov/embuild/issues/16
# For ESP-IDF 5 add `espidf_time64` and for earlier versions - remove this flag: https://github.com/esp-rs/rust/issues/110
#rustflags = ["-C", "default-linker-libraries"]
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32c3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.3"
# Builds against ESP-IDF master (mainline)
#ESP_IDF_VERSION = "master"

WIFI_SSID=""
WIFI_PWD=""
MQTT_BROKER_URL=""
MQTT_PORT=""
MQTT_USERNAME=""
MQTT_PWD=""
MQTT_REMOTE_CTRL_COMMANDS_TOPIC="ctrlCommands"
MQTT_TEMP_DATA_TOPIC="temperatureData"
MQTT_HUMIDITY_DATA_TOPIC="humidityData"